# Generated by Django 6.0.3 on 2026-03-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dia_vencimento',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='aluno',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
    ]
