# Generated by Django 6.0.3 on 2026-05-21 04:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='Categoria')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Categorias com número menor aparecem primeiro no PDV.', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Ex: "João Silva", "Mesa 3", "Quadra 1 – turma das 18h".', max_length=80, verbose_name='Cliente / Mesa')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=10, verbose_name='Status')),
                ('aberta_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aberta em')),
                ('fechada_em', models.DateTimeField(blank=True, null=True, verbose_name='Fechada em')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('estoque', models.PositiveIntegerField(default=0, help_text='Unidades disponíveis. Decrementado automaticamente a cada venda.', verbose_name='Estoque atual')),
                ('foto', models.ImageField(blank=True, help_text='Recomendado: imagem quadrada, mínimo 400×400 px.', null=True, upload_to='pdv/produtos/', verbose_name='Foto')),
                ('disponivel', models.BooleanField(default=True, help_text='Desmarque para ocultar o produto do cockpit sem apagá-lo.', verbose_name='Disponível no PDV')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='pdv.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(default=1, verbose_name='Qtd.')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço unit.')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pdv.comanda', verbose_name='Comanda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='pdv.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da Comanda',
                'verbose_name_plural': 'Itens da Comanda',
            },
        ),
    ]
