# Generated by Django 6.0.3 on 2026-03-13 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quadras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('nome_cliente', models.CharField(max_length=100)),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadras.quadra')),
            ],
            options={
                'unique_together': {('quadra', 'data', 'horario_inicio')},
            },
        ),
    ]
